### PR TITLE
#34 describe the projects purpose

### PR DESCRIPTION
**Pull request by niccokunzmann**
This should describe the projects role inside the Schul-Cloud.

@extremelypenguin Would that solve the issue?

### CODE REVIEW

**Comment by extremelypenguin** [comment]
the rest is alright but i'm still a bit confused as to what schul-cloud as a whole is about

**Comment by niccokunzmann** [comment]
Do you understand German? http://blog.schul-cloud.org/

**Comment by extremelypenguin** [comment]
no, I dont.

**Comment by niccokunzmann** [comment]
Schul-Cloud is a cloud platform for schools. They can organize lessons, files and more. It is developed as a feedback of teachers.

**Comment by extremelypenguin** [comment]
@niccokunzmann that sounds good. We can add that to the readme

**Comment by niccokunzmann** [comment]
Sure.
"Be the change you want to see in the world." :)
I will merge it.

**Pull request merged**
